/**
 * The error reference: one entry per diagnostic code Sygnal reports (the
 * runtime core, the 'sygnal/diagnostics' dev entry, and sygnal-check).
 *
 * This table is the single source for `sygnal-check explain <code>`, the MCP
 * `explain` tool, and the docs' error reference page
 * (https://sygnal.js.org/reference/errors). It is also published as JSON:
 * sygnal-check/explanations.json (`import 'sygnal-check/explanations.json'`),
 * regenerated with `node bin/sygnal-check.js explain --all --json > explanations.json`.
 *
 * test/explanations.vtest.js keeps it in sync with the runtime registry
 * (src/extra/diagnostics/codes.ts in the sygnal repo): every registered code
 * has an entry, with the same title and default severity, and the JSON file
 * matches this table.
 *
 *   title        the registry title
 *   severity     the RUNTIME default severity ('error' = the operation failed: thrown,
 *                or caught and logged with console.error while the app keeps running;
 *                'warn' = likely mistake, printed in 'warn' mode; 'info' = collected
 *                only). A call site may report a lower severity (SYG405, SYG406).
 *                sygnal-check may use a different default for a static finding (see
 *                staticSeverity in getExplanation()).
 *   reportedBy   'runtime'   the sygnal core (always on; includes renderComponent's
 *                            built-in checks)
 *                'dev-entry' the 'sygnal/diagnostics' checks (dev only, diagnostics on)
 *                'static'    sygnal-check (SYG5xx only with --strict)
 *   explanation  what triggers it and what goes wrong (2-4 sentences)
 *   fix          how to fix it
 */
export const EXPLANATIONS = {
  SYG101: {
    title: "Intent action has no model entry",
    severity: "warn",
    reportedBy: ["dev-entry", "static"],
    explanation: "The intent returns an action stream whose name has no matching key in `model` (shorthand keys like `'ACTION | SINK'` count as `ACTION`). Events on that stream are produced but nothing handles them, so the action silently does nothing. Built-in actions (`BOOTSTRAP`, `INITIALIZE`, `DISPOSE`, `READY`, and `RESOURCE`, which the core writes for a `resources` static) and internal `__*` actions are never reported. `HYDRATE` is not built in since 6.0: it is an ordinary action name.",
    fix: "Add a model entry with the same name, e.g. `model = { SAVE: (state) => ({ ...state, saved: true }) }`, or remove or rename the intent action so it matches an existing model key.",
  },
  SYG102: {
    title: "Model entry is unreachable",
    severity: "info",
    reportedBy: ["dev-entry", "static"],
    explanation: "A model entry has no intent action of the same name and is not a built-in action (`BOOTSTRAP`, `INITIALIZE`, `DISPOSE`, `READY`, `RESOURCE`; `HYDRATE` is an ordinary action since 6.0), so nothing in the intent can trigger it. A request also triggers the reply actions it names (`{ url, ok: 'LOADED', error: 'FAILED' }` sent to a driver sink), and so does a `connections` entry (`message`, `open`, `close`, `error`) or a request a `resources` entry derives (`ok`, `error`). A `RESOURCE` entry replaces the built-in reducer that writes `state[name]` for a `resources` static (experimental). It may still be reached through `next('ACTION')`, which the runtime cannot know in advance, so the runtime check reports it as info (and skips components whose intent returns a single stream); it counts the `ok`/`error` string literals it finds in the source of the component's non-STATE sink functions. The static checker also accounts for `next()` calls and reply-action names with string literals and reports it as warn, downgraded to info when a `next()` call or an `ok`/`error` value uses a non-literal name.",
    fix: "Add the action to the component's `intent`, name it in a request (`HTTP: (state) => ({ url, ok: 'ACTION' })`), dispatch it with `next('ACTION')` from another entry, or remove the dead model entry.",
  },
  SYG103: {
    title: "Intent selector matched no rendered element",
    severity: "info",
    reportedBy: ["dev-entry", "runtime"],
    explanation: "A selector passed to `DOM.select()` in the intent has not matched any element the component rendered, so its events never fire (often a typo in the class or id). The dev entry skips selectors whose class/id/tag tokens all appear in the view source (assumed conditionally rendered); others are reported as info on the first check and escalated to warn after at least 3 renders and about 2 s of render-idle time with no match. Under `renderComponent`, `simulateEvent()` on a selector that matches no rendered element throws an error instead; with `{ allowMissing: true }` the event is dropped and SYG103 is reported.",
    fix: "Check the selector against the `className`/`id` in the view. If the element is rendered by a child component, handle the event inside that child instead.",
  },
  SYG104: {
    title: "Intent selector crosses an isolation boundary",
    severity: "warn",
    reportedBy: ["dev-entry", "runtime", "static"],
    explanation: "An intent selector matches nothing in the component's own scope, but does match elements rendered inside a child component or Collection item. Child components are isolated, so the parent's `DOM` source never receives events from those elements and the action never fires. The dev entry checks the real DOM after renders, `renderComponent` checks the mock vtree, and `sygnal-check` finds the class/id only in a child component's view.",
    fix: "Handle the event inside the child component and send it up with `PARENT` (read it in the parent with `CHILD.select(Child)`), or broadcast it with `EVENTS`.",
  },
  SYG105: {
    title: "EVENTS type selected but never emitted, or emitted but never selected",
    severity: "info",
    reportedBy: ["dev-entry", "static"],
    explanation: "An `EVENTS` bus type is emitted with nothing selecting it, or selected with `EVENTS.select(type)` but never emitted. The bus is a broadcast, so an event that nobody has subscribed to when it is emitted is dropped; a mismatched name usually means a typo. At runtime the emitted-not-selected case is reported when the event is emitted, while selected-not-emitted is only reported on demand via `checkEventBus()` (inspect/test helpers); `EVENTS.select()` with no type counts as selecting everything. The static checker compares string-literal types across the scanned files and reports warn, or info when non-literal emits/selects exist.",
    fix: "Make the names match: emit from a model entry, e.g. `{ EVENTS: event('TYPE', data) }`, and subscribe with `EVENTS.select('TYPE')` in the receiving component's intent.",
  },
  SYG106: {
    title: "Parent prop is overwritten by a reserved view argument",
    severity: "warn",
    reportedBy: ["dev-entry"],
    explanation: "The view is called with `{ ...props, state, children, slots, context, peers }`, so a prop named `children`, `slots`, `context` or `peers` passed by the parent is overwritten and never reaches the child. A `state` prop is also reported when its value is not a state lens (a field-name string or a `{ get, set }` object), because Sygnal reads `state` as the child's state lens rather than as data. Reported once per component and prop, as a warning, or as an error in strict mode (`--strict` has no static SYG106 rule; the runtime strict switches are `configureStrict(true)`, `renderComponent(C, { strict: true })`, `run(App, drivers, { diagnostics: { strict: true } })` and `globalThis.__SYGNAL_STRICT__`).",
    fix: "Rename the prop in both parent and child (e.g. `contextValue`, or `item` instead of `state`); to give the child a slice of parent state use `state=\"fieldName\"`.",
  },
  SYG110: {
    title: "Intent selector not present in the component view",
    severity: "warn",
    reportedBy: ["static"],
    explanation: "A class or id selector used in the intent (`DOM.select('.x')`, `DOM.click('.x')`, ...) is never rendered by the component's own view, nor by JSX passed into it as children/slots, so the action never fires. It is reported as info instead of warn when a dynamic `className`/`id` in the view might produce the name, or when the selector itself is not a static string and could not be checked.",
    fix: "Fix the selector to match the view, or add the class/id to the element, e.g. `className=\"x\"`; use a string literal (or module-level const) selector so it can be checked.",
  },
  SYG111: {
    title: "Controlled input has no input listener",
    severity: "warn",
    reportedBy: ["static"],
    explanation: "An `<input>`, `<textarea>` or `<select>` has `value` (or a checkbox/radio has `checked`) set, but the component's intent has no input/change/keyup/keydown listener on it or an ancestor. Sygnal writes the bound value back on every render, so any re-render while the user is typing or clicking resets the field; this also applies to literal values such as `value=\"\"` and to `value={null}`/`checked={null}`, which clear or uncheck the field on every render (only an absent prop leaves a field uncontrolled). A key listener that is immediately filtered to one key (e.g. Enter) does not count.",
    fix: "Update state on input, e.g. `DOM.input('.name').value()` (or `DOM.change(...)` for toggles/selects), or drop the `value`/`checked` prop (not set it to `null`) to leave the field uncontrolled and read it on blur or submit.",
  },
  SYG112: {
    title: "Reply action has no model entry",
    severity: "error",
    reportedBy: ["dev-entry", "static"],
    explanation: "A request sent to a driver with reply actions (`makeFetchDriver`, `driverFromAsync`, the socket driver) names its reply actions, as in `{ url, ok: 'LOADED', error: 'FAILED' }`, and the driver delivers the reply to the sending component as that action. When the component's model has no entry with that name, the reply is dropped, usually because of a typo. The dev entry checks each request with reply actions as it is sent; `sygnal-check` checks string literal `ok`/`error` values returned by non-STATE sinks and the `message`/`open`/`close`/`error` names in a `connections` static. Statically, only names that look like actions (UPPER_SNAKE_CASE) or are close to a model key are reported, because the checker cannot see which driver a sink goes to, and a custom driver may use an `error` field for data.",
    fix: "Use the name of an existing model entry (the message names the closest one), or add the entry: `LOADED: (state, body) => ({ ...state, data: body })`.",
  },
  SYG115: {
    title: "Unknown DOM event shorthand",
    severity: "warn",
    reportedBy: ["dev-entry"],
    explanation: "`DOM.<name>(selector)` is shorthand for `DOM.select(selector).events('<name>')`, and the DOM source accepts any property name, so a made-up name such as `DOM.key('.search')`, `DOM.enter(...)` or `DOM.keyDown(...)` listens for an event the browser never fires: the action silently never happens. The dev entry reports a shorthand call whose name is not a known DOM event, once per component and name. Key names and the enriched-stream helpers (`.key()`, `.value()`, `.checked()`, `.data()`) are not events.",
    fix: "Use the real event and an enriched-stream helper: `DOM.keydown('.search').key()` (add `.filter(k => k === 'Enter')` for one key), `DOM.input('.name').value()`, `DOM.change('.box').checked()`. For a custom event you dispatch yourself, use the explicit form `DOM.select(sel).events('my-event')`, which is never reported.",
  },
  SYG116: {
    title: "EVENTS value has no string type",
    severity: "error",
    reportedBy: ["dev-entry"],
    explanation: "A model sent a value without a string `type` to the `EVENTS` sink, so no `EVENTS.select(type)` can receive it and it is dropped. The usual cause is a function: a model entry that returns `event(...)` (for example `{ EVENTS: () => event('SAVED', data) }`) instead of being `event(...)`, or any other reducer that returns a function. Each emitted value is copied into a new object, so a function arrives on the bus as `{}`. A reducer that returns `undefined` or `null` (see SYG217) causes it too.",
    fix: "Make `event()` the sink entry itself: `SAVE: { EVENTS: event('SAVED', (state, data) => payload) }`; return `ABORT` from a reducer to send nothing.",
  },
  SYG130: {
    title: "href() names no route or leaves out a param",
    severity: "error",
    reportedBy: ["dev-entry"],
    explanation: "`router.href(name, params)` builds a link from the route table passed to `makeRouter({ routes })`. When `name` is not a route (or is the `'*'` not-found route), href() returns the app's root path; when the pattern has a `:param` that `params` leaves out, that segment is empty (`/tasks/`). Either way the link goes somewhere else than intended. The `sygnal/diagnostics` dev entry checks every href() call; production builds don't. A `{ to }` command with the same problem is SYG620.",
    fix: "Use a route name from the table (the message suggests the closest one) and pass every param the pattern names: `href('task', { id: task.id })`.",
  },
  SYG131: {
    title: "Route params the pattern does not use",
    severity: "warn",
    reportedBy: ["dev-entry"],
    explanation: "An href() call or a `{ to, params }` router command passes a param that the route's pattern has no `:name` for. It is ignored, so the value never reaches the URL; usually it was meant for the query string, or the route is the wrong one.",
    fix: "Pass only the pattern's params, and put other values in the query: `href('tasks', {}, { page: 2 })` or `{ to: 'tasks', query: { page: 2 } }`.",
  },
  SYG132: {
    title: "Declaration static that is never sent",
    severity: "warn",
    reportedBy: ["dev-entry"],
    explanation: "Declaration statics (`route`, `resources`, `connections`, `head`) are computed from the component's state and sent to their driver whenever they change, with or without a model. A root component (the one passed to `run()`) with a model but no `initialState` has no state, so its state stream never emits: the route never arrives, the resources never load, the connections never open, the head never changes. Sub-components share their parent's state, so this only happens at the root.",
    fix: "Give the root an `initialState`, even an empty object; for the router, seed the route: `App.initialState = { route: router.current() }`. Don't add an `initialState` to a sub-component that shares its parent's state: it would replace that state (SYG405).",
  },
  SYG133: {
    title: "SPA router inside a Vike app",
    severity: "warn",
    reportedBy: ["dev-entry"],
    explanation: "`makeRouter()` intercepts link clicks and writes the history itself, and so does Vike's client router. Running the SPA router inside a Vike app makes both handle each click and navigation. In Vike, give the router Vike's `navigate()`: it then leaves links and history to Vike, navigates with `navigate()`, and re-reads the route after each Vike navigation.",
    fix: "`makeRouter({ routes, navigate })` with `import { navigate } from 'vike/client/router'`, using a route table that mirrors the Vike routes; or read the route from Vike's page context and drop the router.",
  },
  SYG201: {
    title: "STATE reducer dropped keys from the previous state",
    severity: "warn",
    reportedBy: ["dev-entry"],
    explanation: "A STATE reducer returned a plain object that is missing keys present (and not `undefined`) in the previous state, which usually means a missing `...state` spread. Those keys are silently lost from state. Calculated fields, `INITIALIZE` and internal `__*` actions are excluded; reported once per component and action.",
    fix: "Spread the previous state: `(state, data) => ({ ...state, field: data })`. If removing the keys is intended, ignore the warning.",
  },
  SYG202: {
    title: "STATE reducer returned undefined",
    severity: "warn",
    reportedBy: ["dev-entry"],
    explanation: "A STATE reducer returned `undefined`, typically from a block-bodied arrow function without `return`. In a root component this wipes the state; in a sub-component it is reported as info instead, because returning `undefined` from a Collection item's reducer is the documented way to remove the item. `INITIALIZE` and internal `__*` actions are excluded.",
    fix: "Return the new state, e.g. `(state, data) => ({ ...state, ... })`, or return `ABORT` to leave the state unchanged.",
  },
  SYG206: {
    title: "Invalid calculated field definition",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "An entry in `calculated` is neither a function nor a two-element `[deps, fn]` array where `deps` is an array and `fn` is a function. The component constructor throws, so the component is never created.",
    fix: "Define each field as `state => value` or `[['a', 'b'], state => value]`.",
  },
  SYG207: {
    title: "Calculated field shadows an initialState key",
    severity: "warn",
    reportedBy: ["runtime"],
    explanation: "A key in `calculated` also exists in `initialState`. The calculated value overwrites the stored value of the same name, so the `initialState` value is never visible. Checked once when the component is constructed.",
    fix: "Rename either the calculated field or the `initialState` key.",
  },
  SYG208: {
    title: "Calculated field depends on an unknown key",
    severity: "warn",
    reportedBy: ["runtime"],
    explanation: "A calculated field declared as `[deps, fn]` lists a dependency that is neither another calculated field nor a key of `initialState`. The dependency is likely misspelled, so memoization compares an always-`undefined` value. Only checked when the component has an `initialState`.",
    fix: "Fix the dependency name, or add the key to `initialState`.",
  },
  SYG209: {
    title: "Circular calculated field dependency",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "Calculated fields declared with `[deps, fn]` depend on each other in a cycle (the message shows the path, e.g. `a -> b -> a`), so no evaluation order exists. The component constructor throws.",
    fix: "Break the cycle so that each calculated field depends only on state keys or on fields that do not depend back on it.",
  },
  SYG210: {
    title: "INITIALIZE used with a sink other than STATE",
    severity: "warn",
    reportedBy: ["runtime"],
    explanation: "The model defines `INITIALIZE` as an object with sinks other than the state sink (e.g. `EVENTS` or `EFFECT`). `INITIALIZE` only supports the state sink, so those other sink entries are deleted and never run.",
    fix: "Keep only `STATE` under `INITIALIZE` and move the other sinks to a different action (for example one triggered by `BOOTSTRAP` or via `next()`).",
  },
  SYG211: {
    title: "Invalid model shorthand entry",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A model key contains `|` but does not split into exactly two non-empty parts (e.g. `'SAVE |'` or `'A | B | C'`). Model setup throws when the component is initialized.",
    fix: "Use exactly one action and one sink: `'SAVE | EFFECT': (state) => { ... }`.",
  },
  SYG212: {
    title: "Model entry is not a function or an object of sinks",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A model entry's value is neither a function (a STATE reducer) nor a plain object mapping sink names to reducers; for example a string, number, array or `null`. Model setup throws when the component is initialized.",
    fix: "Use a reducer function or a sink map, e.g. `{ STATE: (state) => ..., EVENTS: ... }`.",
  },
  SYG213: {
    title: "Duplicate model entry for the same action and sink",
    severity: "warn",
    reportedBy: ["runtime"],
    explanation: "The same action and sink pair is defined more than once, which can only happen through shorthand keys (e.g. `'SAVE | STATE'` alongside `SAVE: fn` or `SAVE: { STATE: ... }`). Both entries are merged into the sink, so both reducers run for each action (as the warning says), which is rarely what was meant.",
    fix: "Remove the duplicate so each action/sink pair is defined once.",
  },
  SYG214: {
    title: "EFFECT handler threw",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A model entry on the `EFFECT` sink threw an exception. The error is caught and logged with `console.error` (with the original error attached) rather than thrown, so the app keeps running but the effect did not complete. In diagnostics `error` mode the diagnostic is rethrown asynchronously. If the exception is itself a coded Sygnal error (for example SYG215 from `next()`), it is reported under that code instead.",
    fix: "Fix the exception shown in the attached error, or guard the handler against missing state or data.",
  },
  SYG215: {
    title: "next() delay is not a number",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The third argument of `next(type, data, delay)` was given and is not a number. `next()` throws and the follow-up action is not dispatched. When it is called inside a reducer or EFFECT handler, the handler catches the throw and reports it under this code (not SYG216 or SYG214), so a STATE reducer leaves the state unchanged and a driver-sink reducer sends nothing.",
    fix: "Pass a number of milliseconds, or omit it for the default 10 ms: `next('ACTION', data, 100)`.",
  },
  SYG216: {
    title: "Reducer threw",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A model reducer threw an exception. For a STATE reducer the error is logged and the state is left unchanged; for a driver sink (e.g. `EVENTS`, `PARENT`, custom drivers) it is logged and nothing is sent. The error is logged with `console.error` rather than thrown (rethrown asynchronously in diagnostics `error` mode). A coded Sygnal error thrown inside the reducer (for example SYG215 from `next()`) is reported under its own code instead.",
    fix: "Fix the exception shown in the attached error, or guard the reducer against missing state or data.",
  },
  SYG217: {
    title: "Driver-sink reducer returned undefined",
    severity: "warn",
    reportedBy: ["runtime"],
    explanation: "A reducer for a non-STATE sink (e.g. `EVENTS`, `PARENT` or a custom driver) returned `undefined`, often from a missing `return`. The `undefined` value is still sent to the driver.",
    fix: "Return the value the driver expects, or return `ABORT` to send nothing.",
  },
  SYG218: {
    title: "Reducer returned an unsupported type",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A reducer for a non-STATE sink (e.g. `EVENTS`, `PARENT` or a custom driver) returned a symbol other than `ABORT`. Any other value, including `null`, arrays and bigints, is sent to the driver as-is, like a constant sink value. It is logged with `console.error` (not thrown) and nothing is sent.",
    fix: "Return the value the driver expects, or return `ABORT` to send nothing.",
  },
  SYG219: {
    title: "EFFECT handler returned a value",
    severity: "warn",
    reportedBy: ["runtime"],
    explanation: "An `EFFECT` handler returned something other than `undefined`. EFFECT entries run only for side effects, so the return value is ignored; this usually means the logic was meant for a STATE or driver sink. Returning `ABORT` from an EFFECT also triggers it.",
    fix: "Do not return a value from EFFECT handlers; move value-producing logic to a `STATE` or driver sink entry.",
  },
  SYG220: {
    title: "Calculated field threw",
    severity: "warn",
    reportedBy: ["runtime"],
    explanation: "A calculated field function threw while computing derived state, for example by reading a property of missing data. The error is caught and the field is skipped for that update, so it is not recomputed from the new state.",
    fix: "Guard the calculation against missing data, e.g. `state => state.user?.name ?? ''`.",
  },
  SYG221: {
    title: "set() called with a string",
    severity: "error",
    reportedBy: ["dev-entry"],
    explanation: "`set()` takes an object to merge (`set({ open: true })`) or a function that returns one (`set((state, data) => ({ ... }))`). Called with a field name, `set('city')` spreads the string into the state, adding the keys `'0'`, `'1'`, ... one per character, and the field itself never changes. The dev entry recognises those keys after the reducer runs and reports the field name; TypeScript also rejects a string argument.",
    fix: "To store the action data in a field, pass a function: `set((state, city) => ({ city }))`. For a fixed value pass an object: `set({ city: 'Paris' })`.",
  },
  SYG301: {
    title: "RxJS operator used on an xstream stream",
    severity: "error",
    reportedBy: ["dev-entry"],
    explanation: "An RxJS operator such as `pipe`, `switchMap`, `debounceTime` or `tap` was called on a Sygnal stream, which is an xstream stream and does not have it. With `sygnal/diagnostics` loaded, these names are defined on xstream's `Stream.prototype` to throw a `TypeError` that names the xstream equivalent, instead of the bare `x.switchMap is not a function`. A side effect of the dev entry is that `typeof stream.pipe === 'function'` is true while it is loaded.",
    fix: "Use the xstream equivalent from the message, e.g. `.map(x => inner$).flatten()` for `switchMap`, or `.compose(debounce(ms))` for `debounceTime`.",
  },
  SYG401: {
    title: "Collection 'from' field is missing or not an array",
    severity: "warn",
    reportedBy: ["runtime", "dev-entry", "static"],
    explanation: "A `<Collection>` needs an array to render. The runtime reports this when `from=\"field\"` names a key that is not in the parent state (or its calculated fields), when that field is not an array, or when a `from={{ get, set }}` getter returns a non-array; the dev entry also reports a `<Collection>` with no `from` whose parent state is not an array. In every case the Collection silently renders no items. `sygnal-check` reports the same mistake statically when `from` is not a key of a statically known `initialState`, or its initial value is a literal that is clearly not an array.",
    fix: "Point `from` at an array field and initialize it in `initialState`, e.g. `initialState = { items: [] }` with `<Collection of={Item} from=\"items\" />`, or make a custom `get()` return an array.",
  },
  SYG402: {
    title: "Context is not an object",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The component's `.context` is set to something other than a plain object (for example a function or an array). It is logged and ignored: the component contributes no context values, and descendants only receive the context inherited from further up. It is logged, not thrown, so rendering continues.",
    fix: "Define context as an object of named entries: `Comp.context = { theme: state => state.theme }`.",
  },
  SYG403: {
    title: "Invalid context entry",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A `.context` entry value is not a state key string, a boolean, or a function of state. That entry is skipped each time context is computed, so descendants read `undefined` for it; the other entries still work. It is logged, not thrown.",
    fix: "Use a state key string (`{ user: 'currentUser' }`), `true` to copy the same-named state key, or a function (`{ user: state => state.currentUser }`).",
  },
  SYG404: {
    title: "Context stream errored",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The stream that computes a component's context emitted an error, most often because a context function threw. An errored xstream stream stops, so this component's context stops updating for its descendants from that point on. The original error is attached to the log.",
    fix: "Check the attached error and make each context function safe for every state it can receive (e.g. guard against missing fields with `state.user?.name`).",
  },
  SYG405: {
    title: "Sub-component has initialState without isolatedState",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A sub-component defines `initialState` but not `isolatedState = true`, so its `initialState` would overwrite the state slice its parent passes in. For a component rendered by tag in a parent's view this is an error: it is thrown when the child is instantiated, and the parent catches it, logs it under this code and renders its error fallback instead of the child. For Collection items and Switchable children it is only a warning and the initial state still replaces what the parent passed.",
    fix: "Remove `initialState` from the sub-component and let the parent own the state, or set `Child.isolatedState = true` if the child should keep its own local state.",
  },
  SYG406: {
    title: "View threw",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The component's view function threw while rendering. The error is logged and the component renders its `onError` fallback if it has one, or an empty `<div data-sygnal-error>` otherwise. The app keeps running, but that component shows no real content until a later render succeeds.",
    fix: "Fix the error in the view (often a missing field on `state` or `props`), and add `Comp.onError = (error, { componentName }) => <div>…</div>` if you want a custom fallback.",
  },
  SYG407: {
    title: "onError handler threw",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A component's `onError` handler threw while handling a view error (SYG406) or a sub-component instantiation error (SYG408). Sygnal logs the second error and renders an empty `<div data-sygnal-error>` instead of your fallback.",
    fix: "Keep `onError` simple and make it always return a vnode, e.g. `Comp.onError = () => <div class=\"error\">Something went wrong</div>`.",
  },
  SYG408: {
    title: "Sub-component failed to instantiate",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "Creating a sub-component (a custom component, Collection, or Switchable found in the parent's view) threw an uncoded exception, for example from the child's intent. The parent catches it, logs it with the original error attached, and renders its own `onError` fallback, or an empty `<div data-sygnal-error>`, in that child's place. The rest of the parent keeps rendering. A coded Sygnal error thrown while instantiating (SYG405, SYG413, SYG414, SYG903, ...) is reported under its own code instead, with the same fallback.",
    fix: "Read the attached error and fix its cause.",
  },
  SYG409: {
    title: "Child tried to update a calculated field",
    severity: "warn",
    reportedBy: ["runtime"],
    explanation: "A sub-component, Switchable, or Collection is bound to a parent state field (via its `state` or `from` prop) that is one of the parent's `calculated` fields, and the child wrote a new value back to it. Calculated fields are derived from other state, so the write is ignored and the parent state is left unchanged.",
    fix: "Bind the child to a plain (non-calculated) state field, and change the fields the calculated value is derived from instead.",
  },
  SYG410: {
    title: "Invalid sub-component 'state' prop",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The `state` prop on a sub-component or Switchable is neither a state key string nor an object with a `get()` function (for example a number, or a `{ set }` object without `get`). It is logged and the child falls back to receiving the parent's whole state, which is usually not what was intended.",
    fix: "Pass a state key string (`state=\"user\"`) or a lens object `state={{ get: s => s.user, set: (s, user) => ({ ...s, user }) }}`.",
  },
  SYG411: {
    title: "Collection 'of' is missing or not a component",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A `<Collection>` has no `of` prop, `of` is not a function or string, or `of` is a string that does not name a component registered in `.components`. This is thrown while the parent's view is processed, so the Collection cannot render. It is also thrown when the exported `collection()` helper is called with a first argument that is not a function.",
    fix: "Pass the item component function itself: `<Collection of={TaskCard} from=\"tasks\" />`.",
  },
  SYG412: {
    title: "Invalid Collection 'from' prop",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The `from` prop on a `<Collection>` is neither a state key string nor an object with a `get()` function. It is logged (not thrown) and the Collection renders nothing.",
    fix: "Use a state key string (`from=\"items\"`) or a lens object with `get` and `set`: `from={{ get: s => s.items, set: (s, items) => ({ ...s, items }) }}`.",
  },
  SYG413: {
    title: "Unnamed component factory not found",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The view rendered an unnamed component element (`sygnal-factory`) that carries no component factory or options, so Sygnal has nothing to instantiate. The throw is caught by the parent, which logs it under this code and renders its error fallback in that place.",
    fix: "Render the component by referencing a named function in JSX, or give it a stable name with `Comp.componentName = 'Comp'`.",
  },
  SYG414: {
    title: "Component not found",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The view rendered a component by name, but no factory for that name exists in the parent's `.components` and none was attached to the element. The throw is caught by the parent, which logs it under this code and renders its error fallback in that place.",
    fix: "Import the component and use it directly as a JSX tag, or register it in the parent's `.components` under the name you render.",
  },
  SYG415: {
    title: "Switchable 'of' is missing or invalid",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A `<Switchable>` has no `of` prop, `of` is not a plain object, or one of its values is not a component function. This is thrown while the parent's view is processed, so the Switchable cannot render.",
    fix: "Pass an object mapping names to components: `<Switchable of={{ list: ListView, grid: GridView }} current={state.mode} />`.",
  },
  SYG416: {
    title: "Switchable 'current' is missing or invalid",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A `<Switchable>` has no `current` prop, `current` is not a string or function, or `current` is not one of the keys of `of`. This is thrown while the parent's view is processed, so no component can be shown.",
    fix: "Set `current` to one of the keys of `of`, e.g. `current=\"list\"` when `of={{ list: ListView, grid: GridView }}`, and make sure the state value it comes from is initialized.",
  },
  SYG417: {
    title: "Portal target not found",
    severity: "warn",
    reportedBy: ["runtime"],
    explanation: "A `<Portal target=\"…\">` selector matched no element in the document. Sygnal retries for a short time (about 10 attempts, 5 ms apart) in case the target is rendered by a sub-component that has not settled yet, then warns and leaves the portal content unrendered.",
    fix: "Make sure an element matching the `target` selector exists in the page (for example `<div id=\"modal-root\">` in your HTML) before the Portal mounts.",
  },
  SYG418: {
    title: "Invalid Collection sort prop",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The `sort` prop on a `<Collection>` has an unsupported shape: an object with more than one key, a direction that is not `'asc'`, `'desc'`, `1` or `-1`, or a value that is not a string, array, object or function. The invalid sort (or array element) is logged and ignored, so the items are not sorted as intended.",
    fix: "Use a field name (`sort=\"title\"`), a single-key object (`sort={{ title: 'desc' }}`), a comparator function, or an array of these.",
  },
  SYG419: {
    title: "Invalid switchable() 'name$' parameter",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The exported `switchable()` helper was called without a `name$` argument, or with one that is not a stream, a state key string, or a function of state. It throws immediately because it cannot tell which component to show.",
    fix: "Pass a stream of component names, a state key string, or a `state => name` function as the second argument to `switchable()`.",
  },
  SYG420: {
    title: "JSX tag is undefined",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A JSX element's tag evaluated to `undefined`, usually because a component was not imported, was misspelled, or was imported as default instead of named (or vice versa). Sygnal renders an `<UNDEFINED>` element in its place and logs the message with `console.error`; it is collected like other runtime diagnostics (the JSX runtime reports it through the diagnostics core, or only prints it when no Sygnal core is loaded).",
    fix: "Import or define the component in the file that uses it, and check that the import style (default vs named) matches the export.",
  },
  SYG421: {
    title: "Invalid data (dataset) key",
    severity: "error",
    reportedBy: ["dev-entry"],
    explanation: "A view renders a `data` key the DOM can't store. `data={{ ... }}` is written with `element.dataset[key] = value`, and the browser throws a SyntaxError DOMException for a key with a hyphen followed by a lower-case letter (`'task-id'`), or an attribute-name error for characters such as spaces, quotes or `=`. The patch fails, so rendering can stop, and the console shows only a bare `DOMException {}`. The dev entry checks every rendered dataset key before the patch and names the key; renderComponent's mock DOM never throws, so it is also the only signal there.",
    fix: "Use a camelCase key in the `data` prop: `data={{ taskId: 7 }}` renders `data-task-id=\"7\"` (a `data-task-id=\"7\"` JSX attribute works too); read it with `.data('taskId')`.",
  },
  SYG501: {
    title: "View uses positional arguments",
    severity: "warn",
    reportedBy: ["dev-entry", "static"],
    explanation: "Strict mode only. The view declares more than one parameter and reads `state`, `context` or `peers` positionally, as in `function Lane(props, state)`, instead of destructuring them from its first argument. The canonical form keeps every view's signature the same, so code and tooling can rely on it. The runtime check uses the function's declared arity, so a default value or rest parameter can hide a positional use.",
    fix: "Destructure the first argument: `function Lane({ state, context, ...props })`.",
  },
  SYG502: {
    title: "STATE reducer signals no change without ABORT",
    severity: "warn",
    reportedBy: ["dev-entry", "static"],
    explanation: "Strict mode only. A STATE reducer signals \"no change\" by returning the previous state object instead of `ABORT`; at runtime it is reported when the reducer returns the same object it received. `sygnal-check --strict` also flags `return state`, a bare `return;`, and a block body that can reach its end without returning. An explicit `return undefined` is not flagged statically, because that is how a Collection item removes itself.",
    fix: "Return `ABORT` for \"no change\": `TOGGLE: (state, data) => cond ? { ...state, open: !state.open } : ABORT`.",
  },
  SYG503: {
    title: "Side effect in a STATE reducer that returns ABORT",
    severity: "warn",
    reportedBy: ["static"],
    explanation: "Strict mode only (`sygnal-check --strict`). A STATE reducer runs a call whose result is unused (such as `cmd.send('play')`, `next('X')` or `localStorage.setItem(…)`) and then returns `ABORT`. This is the old pattern for side effects; the canonical form puts side effects in an `EFFECT` sink so STATE reducers stay pure. The check is a heuristic.",
    fix: "Move the side effect to an EFFECT sink: `PLAY: { EFFECT: (state, data, next) => { cmd.send('play') } }`, keeping any state change in `STATE`.",
  },
  SYG504: {
    title: "'ACTION | SINK' shorthand model key",
    severity: "warn",
    reportedBy: ["dev-entry", "static"],
    explanation: "Strict mode only. A model key uses the `'ACTION | SINK'` shorthand, such as `'SEND | EFFECT': …`. It works, but the canonical form is the object form, which keeps every sink an action drives in one place. `sygnal-check --strict --fix` rewrites it automatically when no other entry handles the same action.",
    fix: "Use the object form: `SEND: { EFFECT: (state, data, next) => … }`, merging into an existing `SEND` entry if there is one.",
  },
  SYG505: {
    title: "Non-canonical EVENTS emit",
    severity: "warn",
    reportedBy: ["static"],
    explanation: "Strict mode only (`sygnal-check --strict`). A model entry emits a global event with `emit('TYPE', fn)` (as the whole entry or spread into the object form), or its EVENTS sink builds the `{ type: 'TYPE', data }` object by hand. The canonical form is an `EVENTS` sink using `event()` inside the object form. `--fix` rewrites the common cases and adds the `event` import.",
    fix: "Use `ACTION: { EVENTS: event('TYPE', (state, data) => payload) }`.",
  },
  SYG506: {
    title: "CHILD.select() with a string component name",
    severity: "warn",
    reportedBy: ["static"],
    explanation: "Strict mode only (`sygnal-check --strict`). An intent calls `CHILD.select('TaskCard')` with the child's name as a string. Matching by name breaks when a minifier renames the component function, so the parent silently stops receiving the child's PARENT output in production builds. `--fix` replaces the string with the identifier when that name is in scope.",
    fix: "Pass the component function: `CHILD.select(TaskCard)` (import it first if needed).",
  },
  SYG507: {
    title: "Prop drilled through more than 2 component levels",
    severity: "info",
    reportedBy: ["static"],
    explanation: "Strict mode only (`sygnal-check --strict`). A component receives a prop from its parent and passes it on unchanged, under the same name, to its own child component, so the value crosses three component levels. Data that flows that far down belongs in `.context`, which reaches every descendant without each level forwarding it. This is informational only.",
    fix: "Provide the value as context on the top component, e.g. `Parent.context = { theme: state => state.theme }`, and read `context.theme` where it is needed.",
  },
  SYG508: {
    title: "select()/errors() round trip where reply actions would do",
    severity: "warn",
    reportedBy: ["dev-entry", "static"],
    explanation: "Strict mode only. A component sends a request with `category: 'quote'` to a driver with reply actions (`makeFetchDriver`, `driverFromAsync`, or a sink named `HTTP`) and reads the reply back in its own intent with `HTTP.select('quote')` or `HTTP.errors('quote')`. The canonical form is a request with reply actions: it names them in the request, so the intent line, the category string and the select/errors split all go away, and the reply reaches exactly the component instance that sent it. `select()`/`errors()` remain for requests without reply actions and for stream-level composition (see Alternative forms). The runtime check (`configureStrict(true)`, `renderComponent(C, { strict: true })`) reports a request whose category the same component selects on a source with reply actions.",
    fix: "Name the reply actions in the request and remove the intent line: `LOAD: { HTTP: (state) => ({ url: '/api/quote', ok: 'LOADED', error: 'FAILED' }) }`, with `LOADED: (state, body) => …` (the parsed body) and `FAILED: (state, { status }) => …` in the model.",
  },
  SYG601: {
    title: "Missing or invalid sources",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A component was created or called without a sources object, or with sources that are not a plain object. This happens when a component factory is called by hand instead of through `run()` (or `renderComponent()`), or with the wrong argument. It is thrown, because no part of the component can be wired without sources.",
    fix: "Start the app with `run(RootComponent)` and let Sygnal pass sources, or pass a sources object when calling a component factory directly.",
  },
  SYG602: {
    title: "Intent is not a function",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The component's `.intent` is set but is not a function (for example an object of streams). It is thrown when the component is constructed.",
    fix: "Make intent a function of sources: `Comp.intent = ({ DOM }) => ({ CLICK: DOM.select('.btn').events('click') })`.",
  },
  SYG603: {
    title: "Intent returned an invalid value",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The intent function returned something other than a stream or an object of streams, often `undefined` because an arrow function used a block body without `return`. It is thrown when the component is constructed.",
    fix: "Return an object of action streams, e.g. `intent = ({ DOM }) => ({ CLICK: DOM.select('.btn').events('click') })` (note the parentheses around the object).",
  },
  SYG604: {
    title: "Invalid hmrActions",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The component's `hmrActions` is neither an action name string nor an array of action name strings. It is thrown when the component is constructed.",
    fix: "Use a string or an array of strings: `Comp.hmrActions = ['REFRESH']`.",
  },
  SYG605: {
    title: "Intent action name contains '|'",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "An intent returns an action whose name contains `|`. The `|` character is reserved for the `'ACTION | SINK'` model shorthand, so such a name would collide with shorthand keys. It is thrown when the component's actions are wired.",
    fix: "Rename the action so it contains no `|`, e.g. `SAVE_OR_CLOSE` instead of `SAVE|CLOSE`.",
  },
  SYG606: {
    title: "calculated is not an object",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The component's `.calculated` is set but is not a plain object (for example a function or an array). It is thrown the first time calculated fields are added to an object state.",
    fix: "Define calculated fields as an object: `Comp.calculated = { total: state => state.items.length }`.",
  },
  SYG607: {
    title: "State source not found",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A `switchable()` created with a state key string or a state function was given sources that contain no state source under the configured `stateSourceName` (nor `STATE` or `state`). It is thrown because the current component name cannot be read from state.",
    fix: "Include the state source in the sources passed to the switchable, or set `stateSourceName` to the name your state source uses.",
  },
  SYG608: {
    title: "Strict mode requested without the diagnostics entry",
    severity: "warn",
    reportedBy: ["runtime"],
    explanation: "`run(App, drivers, { diagnostics: { strict: true } })` was called but the `sygnal/diagnostics` dev entry is not loaded. The strict (canonical-form) checks live in that entry, so no strict findings are reported; the option still turns diagnostics on. Printed once per page load.",
    fix: "Import the dev entry before `run()` in development (`import 'sygnal/diagnostics'`), or use the Sygnal Vite plugin, which injects it in dev. Do not ship it in production builds.",
  },
  SYG609: {
    title: "Sink or source has no driver",
    severity: "warn",
    reportedBy: ["dev-entry"],
    explanation: "A component's model sends to a sink (for example `HTTP: (state) => ({ url: '/api/x' })`), or its intent reads a source (`HTTP.select('x')`), but `run()` got no driver with that name. Values sent to a sink without a driver are dropped silently, and a source without a driver is `undefined`, so the intent then fails with \"Cannot read properties of undefined\". `renderComponent()` does not report this: in tests it records such sinks (`t.requests(name)`) and fakes such sources (`t.respond` / `t.fail`).",
    fix: "Pass the driver to `run()` under exactly that name: `run(App, { HTTP: makeFetchDriver() })` for HTTP requests, `driverFromAsync(fn)` for any promise-returning function, or your own driver. Check the spelling against the drivers you pass.",
  },
  SYG610: {
    title: "Request has a 'then' or 'catch' key",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A request sent to a driver with reply actions (`makeFetchDriver`, `driverFromAsync`) has a `then` or `catch` key, for example `HTTP: (state) => ({ url: '/api/x', then: 'LOADED' })`. An object with a `then` key is a thenable, so it breaks anything that `await`s it, and these keys look like a promise chain but do nothing. The driver does not send the request.",
    fix: "Name the reply actions with the `ok` / `error` keys: `{ url: '/api/x', ok: 'LOADED', error: 'FAILED' }`. The `ok` action gets the parsed body, the `error` action `{ error, status, body, request }`.",
  },
  SYG611: {
    title: "Socket message not sent or connection not opened",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A value sent to a `makeSocketDriver()` sink could not be acted on. Either a send (`{ to: 'room', json }`) names a connection that this component instance has not declared, that has closed for good (`reconnect: false`, or a URL the browser rejected), or that is a server-sent events connection, which is read-only. Or a declared connection has neither a `socket` nor an `sse` URL. Or the value is neither `{ connections }` nor `{ to, … }`. Connection names are per component instance: a parent cannot send on a child's connection. The message is dropped; a connection that is only (re)connecting is not an error, its sends are queued.",
    fix: "Declare the connection first, `{ connections: { room: { socket: '/ws/rooms/general', message: 'RECEIVED' } } }`, then send on it from the same component: `{ to: 'room', json: { text } }`. Use a WebSocket (`socket:`) for two-way traffic.",
  },
  SYG620: {
    title: "Router command not performed",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "A value sent to the router's sink (`makeRouter().driver`) could not be acted on, so nothing was navigated. Either `{ to }` names no route (or the `'*'` not-found route), or the route's pattern needs a param that `params` leaves out, or the value uses the `route` key, which is reserved for the component's `route` declaration (`App.route = 'ROUTE'`), or it is none of the router's commands. The router reports this in production too.",
    fix: "Navigate with `{ to: 'task', params: { id } }` (plus `query`, `hash`, `replace` as needed), `{ url: router.href(...) }`, `{ back: true }`, `{ forward: true }`, `{ block: 'CONFIRM_LEAVE' }` or `{ prefetch: 'task', params }`.",
  },
  SYG630: {
    title: "Cached request is not idempotent",
    severity: "warn",
    reportedBy: ["dev-entry"],
    explanation: "A request to `makeFetchDriver()` sets `cache: true` or `staleTime` but is not a GET or HEAD (a request with `json` or `body` defaults to POST), for example `{ url: '/api/quotes', method: 'POST', json, cache: true }`. The driver caches its reply by method, URL and body, so a second identical write within `staleTime` is answered from the cache and never reaches the server, and identical writes in flight share one fetch. Writes should always be sent.",
    fix: "Remove `cache` / `staleTime` from the write. To refresh cached reads after it succeeds, tag the reads (`tags: ['quotes']`) and add `invalidates: ['quotes']` to the write.",
  },
  SYG631: {
    title: "validate is not a Standard Schema",
    severity: "error",
    reportedBy: ["dev-entry"],
    explanation: "A request or resource to `makeFetchDriver()` has a `validate` value that is not a Standard Schema, an object with a `~standard.validate` function (zod, valibot and arktype schemas are). A plain function or another validator's object does not qualify. The driver cannot validate the reply, so the request fails with a TypeError on its `error` action (or as the resource's error).",
    fix: "Pass the schema object itself: `validate: QuoteSchema` (for zod, `z.object({ ... })`). To check a body with your own function, use `parse: (res) => res.json().then(check)` instead.",
  },
  SYG632: {
    title: "invalidate matched nothing",
    severity: "info",
    reportedBy: ["dev-entry"],
    explanation: "A `{ invalidate }` value sent to `makeFetchDriver()` matched no cache entry and no mounted resource, so nothing was refetched or marked stale. Tags are explicit: `{ invalidate: 'quotes' }` matches only requests with `tags: ['quotes']`; a string starting with '/' is a prefix of the request's `url` as written (without the driver's `baseUrl`); a function is called with each request. This is info: invalidating data that no component shows at the moment is often fine.",
    fix: "Add `tags: ['quotes']` to the resources (or cached requests) the write should refresh, or invalidate by URL prefix: `{ invalidate: '/quotes' }`.",
  },
  SYG633: {
    title: "abort names a lane the requests do not use",
    severity: "warn",
    reportedBy: ["dev-entry"],
    explanation: "`{ abort: 'X' }` cancels this component instance's requests whose key is 'X'; a request's key is its `key`, else its `ok` action, else its `error` action. The instance sends its `ok: 'X'` requests with another `key`, so the abort matches none of them and they still deliver. (G-175.)",
    fix: "Abort by that key: `{ abort: true, key: 'search' }`, or drop `key` from the requests so their lane is the `ok` action.",
  },
  SYG634: {
    title: "latest: true with a computed key",
    severity: "info",
    reportedBy: ["static"],
    explanation: "A request has `latest: true` and a `key` that is not a string literal, for example `key: 'search-' + state.q`. `latest` cancels this instance's earlier requests with the same key, so a key that changes with state gives every value its own lane, and a new request never cancels the previous one: out-of-order replies can still arrive. That is right for independent lanes, such as one save per row, so this is info.",
    fix: "Use a fixed key (`key: 'search'`) or none (the lane is the `ok` action) so the newest request cancels the others. Keep a computed key only for lanes that should run side by side (`// sygnal-ignore SYG634`).",
  },
  SYG900: {
    title: "A diagnostics check threw",
    severity: "warn",
    reportedBy: ["dev-entry", "static"],
    explanation: "A diagnostics check itself crashed: one of the `sygnal/diagnostics` runtime checks threw inside a hook, or a `sygnal-check` rule threw (or a file could not be parsed). The failure is isolated, so the app and the other checks keep running, but that check produced no results for the code involved. This points to a bug in the checker, or (for parse errors) a syntax error in your file.",
    fix: "For a parse error, fix the syntax error in the named file; otherwise please report it to Sygnal with the file or component that triggers it.",
  },
  SYG901: {
    title: "Sub-component sink stream errored",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The stream that merges a component's sub-component sinks emitted an error. The error is logged with the original error attached; because an errored xstream stream stops, sinks from that component's sub-components can stop flowing afterwards.",
    fix: "Read the attached error and fix its source, usually a reducer, view or driver stream in one of the sub-components.",
  },
  SYG902: {
    title: "EFFECT stream errored",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "The stream that runs a component's `EFFECT` model entries emitted an error. It is logged with the original error attached, and the component's EFFECT handlers stop running from then on, so later side effects are silently skipped.",
    fix: "Read the attached error and fix the action stream or EFFECT handler that caused it; catch expected failures inside the handler.",
  },
  SYG903: {
    title: "Component factory returned invalid sinks",
    severity: "error",
    reportedBy: ["runtime"],
    explanation: "When instantiating a sub-component, Collection, or Switchable, the factory returned something that is not a sinks object. It is thrown during instantiation; the parent catches it, logs it under this code, and renders its error fallback in that place. This usually means a custom factory passed in place of a Sygnal component is not returning sinks.",
    fix: "Make the factory return an object of sink streams, or pass a regular Sygnal component function instead.",
  },
}
